[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "max-age=3600"

[[headers]]
  for = "/*.(ico|js|jpg|jpeg|png|gif)"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
